# k-Fold Cross Validation

What is k-Fold Cross Validation?
>  k-Fold introduces a new way of splitting the dataset which helps to overcome the test only once bottleneck.

How k-Fold work?
1. Choose number of folds value means **K** value. usually we are select 5 or 10.basically value is less then dataset length.
2. Now splite dataset in equal part like number of folds same as k value time.
3. Then k – 1 folds as the training set and remaining fold will be the test set.
4. Train the model on the training set. 
5. Validate on the test set
6. Save the result of the validation
7. we have to repeat step same as k value times.


In [2]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [5]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
print(X)

[[1.90e+01 1.90e+04]
 [3.50e+01 2.00e+04]
 [2.60e+01 4.30e+04]
 [2.70e+01 5.70e+04]
 [1.90e+01 7.60e+04]
 [2.70e+01 5.80e+04]
 [2.70e+01 8.40e+04]
 [3.20e+01 1.50e+05]
 [2.50e+01 3.30e+04]
 [3.50e+01 6.50e+04]
 [2.60e+01 8.00e+04]
 [2.60e+01 5.20e+04]
 [2.00e+01 8.60e+04]
 [3.20e+01 1.80e+04]
 [1.80e+01 8.20e+04]
 [2.90e+01 8.00e+04]
 [4.70e+01 2.50e+04]
 [4.50e+01 2.60e+04]
 [4.60e+01 2.80e+04]
 [4.80e+01 2.90e+04]
 [4.50e+01 2.20e+04]
 [4.70e+01 4.90e+04]
 [4.80e+01 4.10e+04]
 [4.50e+01 2.20e+04]
 [4.60e+01 2.30e+04]
 [4.70e+01 2.00e+04]
 [4.90e+01 2.80e+04]
 [4.70e+01 3.00e+04]
 [2.90e+01 4.30e+04]
 [3.10e+01 1.80e+04]
 [3.10e+01 7.40e+04]
 [2.70e+01 1.37e+05]
 [2.10e+01 1.60e+04]
 [2.80e+01 4.40e+04]
 [2.70e+01 9.00e+04]
 [3.50e+01 2.70e+04]
 [3.30e+01 2.80e+04]
 [3.00e+01 4.90e+04]
 [2.60e+01 7.20e+04]
 [2.70e+01 3.10e+04]
 [2.70e+01 1.70e+04]
 [3.30e+01 5.10e+04]
 [3.50e+01 1.08e+05]
 [3.00e+01 1.50e+04]
 [2.80e+01 8.40e+04]
 [2.30e+01 2.00e+04]
 [2.50e+01 7.90e+04]
 [2.70e+01 5.

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [11]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
X_train

array([[ 0.60603081, -0.9027491 ],
       [-0.54012675,  1.47580428],
       [ 0.03295203, -0.57973568],
       [-0.54012675,  1.91627713],
       [ 1.37013584, -1.43131652],
       [ 1.46564897,  1.00596657],
       [ 0.12846516, -0.81465453],
       [ 0.03295203, -0.25672226],
       [-0.15807423, -0.57973568],
       [-0.15807423, -0.19799255],
       [-0.25358736, -1.3138571 ],
       [-0.25358736, -0.57973568],
       [ 0.41500455,  0.09565602],
       [ 0.89257019, -0.60910054],
       [ 2.03872775, -1.19639767],
       [ 1.08359645, -0.13926283],
       [ 0.70154394,  1.7988177 ],
       [-0.63563988,  0.56549373],
       [ 0.79705706,  0.35993973],
       [ 0.89257019, -0.55037082],
       [-1.11320552, -1.60750566],
       [ 2.13424088,  0.94723686],
       [ 0.03295203,  1.24088543],
       [ 0.22397829,  1.09406114],
       [ 0.41500455, -0.49164111],
       [-0.25358736, -0.31545197],
       [ 0.98808332, -0.84401939],
       [ 0.98808332,  1.88691227],
       [ 0.03295203,

In [12]:
#Training the Kernel SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[64  4]
 [ 3 29]]
0.93


In [17]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)

print("Accuracies: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100)) # how much varience  diff. b/w the all  accuracies


Accuracies: 90.00 %
Standard Deviation: 6.83 %


In [18]:
for i in enumerate(accuracies):
    print(i) # 10 folds different accuracy

(0, 0.8)
(1, 0.9666666666666667)
(2, 0.8)
(3, 0.9666666666666667)
(4, 0.8666666666666667)
(5, 0.8333333333333334)
(6, 0.9)
(7, 0.9333333333333333)
(8, 1.0)
(9, 0.9333333333333333)
